name: Deploy production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@b87ddeff0013ea4c509514f51dd2d3f4eaf0e1d8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd nika
            git pull origin master
            npm ci --production
            pm2 restart nika
