name: Lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  lint:
    strategy:
      matrix:
        dir: [bot, api]
    name: Lint ${{ matrix.dir }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node.js dependencies
        working-directory: ./${{ matrix.dir }}
        run: npm ci

      - name: Run linters
        working-directory: ./${{ matrix.dir }}
        run: npm run lint
